### ISSUE TITLE
"api/PluggableUSB.h: No such file or directory" Are other Arduino Boards Supported?

### ISSUE THREAD

**Issue by 7HE-W0R1D** [microsoft/ArduinoHidForWindows#1]
Hi! I'm trying to play with this library to build an ARGB controller with Windows dynamic lighting. I have an Arduino UNO and a Pro Micro (AT Mega 32U4), however both are complaining about "api/PluggableUSB.h: No such file or directory". The full message is:
`C:\Users\WBR1\OneDrive - UW\Documents\Arduino\libraries\Microsoft_HidForWindows\src\Microsoft_HidDevice.cpp:9:14: fatal error: api/PluggableUSB.h: No such file or directory
#include "api/PluggableUSB.h"
^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Error during build: exit status 1`

I saw in the document that an Arduino Zero with SAMD21 core is used, does that mean other boards are not supported? If not, do you mind to share some insights on how to solve this error?

**Comment by matwilli** [comment]
The problem with the UNO chipset is that it doesn't support 'Native USB', unlike the SAMD21 chipsets in the Arduino Zero.  So, the USB-endpoints can't be changed from the default serial endpoints; necessary for this implementation.  You'll experience this same problem if try to use the [Arduino libraries](https://www.arduino.cc/reference/en/language/functions/usb/keyboard/) for keyboard/mouse etc...

There may be other boards that have the necessary hardware support, but I haven't validated this implementation with them.

**Comment by 7HE-W0R1D** [comment]
Thanks for the reply! I've also tested with the Pro micro 32u4 which I used as an HID device before but still receives the error. 

I saw in the Arduino Library Manager that only SAMD Arduinos are supported. Could the error be caused by the different file structure for AVR core and SAMD 21 core? I see an USB subfolder under `cores/arduino` here https://github.com/arduino/ArduinoCore-samd/tree/master/cores/arduino However under the official AVR core there is no such folder. I tried to replace the "api/PluggableUSB.h" with just "PluggableUSB.h", then it loads the file but errors in some other places.

I'm not an expert in Arduino cores so definitely correct me if I'm wrong :) It would be great if you can provide support for AVR 32u4 Arduinos as they are also commonly used HID controllers.

Cheers

**Comment by matwilli** [comment]
I don't have a controller with that particular AVR chipset on-hand, so I can't validate whether the underlying USB implementation is working.  I've previously tried to get a couple of Adafruit SAMD21 controllers to work, but they are still using an Arduino core that has several known bugs in it.

Any contributions for additional controllers/platforms are certainly welcome!

**Comment by 7HE-W0R1D** [comment]
I took a closer look at the code and changed the include part in `Microsoft_HidDevice.cpp` to the following 
```
#if __has_include("USB/PluggableUSB.h")
    #include "USB/PluggableUSB.h"
#elif __has_include("api/PluggableUSB.h")
    #include "api/PluggableUSB.h"
#else
    #include "PluggableUSB.h"
#endif
```

Things are loading now but raises a new error 
```
[Starting] Verifying sketch 'examples\LampArray\LampArray.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
In file included from xxx\Arduino\libraries\Microsoft_HidForWindows\src/Microsoft_HidConsumerControl.h:12:0,
from xxx\Arduino\libraries\Microsoft_HidForWindows\src/Microsoft_HidForWindows.h:6,
from xxx\ArduinoHidForWindows\examples\LampArray\LampArray.ino:4:
xxx\Arduino\libraries\Microsoft_HidForWindows\src/Microsoft_HidDevice.h:15:1: error: expected class-name before '{' token
{
^
Error during build: exit status 1
[Error] Failed to read or write IntelliSense configuration: {}
[Error] Verifying sketch 'examples\LampArray\LampArray.ino': Exit with code=1
```

Seems like the `PluggableUSBModule` is not initialized? However I did some search and the following post might be helpful. [https://forum.arduino.cc/t/fatal-error-pluggableusb-h-no-such-file-or-directory/1132054/5](https://forum.arduino.cc/t/fatal-error-pluggableusb-h-no-such-file-or-directory/1132054/5) 

Would love to test with 32u4 boards if needed!

**Comment by matwilli** [comment]
Hmmm... that does seem pretty positive direction.

I've secured a Leonardo device (with the same chipset), so I'll try and give this a look over during the week.  Hopefully it's something small :)

**Comment by 7HE-W0R1D** [comment]
Thanks for looking into it! Would be happy to help if you need me to test it 👍

**Comment by stevetrease** [comment]
I've also been trying (and failing) to get this to work with a Leonardo. I'm seeing the same PluggableUSB errors. Happy to help to test a solution if needed.

**Comment by matwilli** [comment]
I've come up short on this :(.

I can fix the compilation error (`PluggableUSB.h` in a different location, and including it directly in `Microsoft_HidDevice.h`), but the underlying USB hardware is different, and I can't get it to work correctly with Get-Feature (Control) reports.

Having Feature-reports work on the Arduino Zero was a big challenge, requiring a lot of debugging (but had the advantage of a hardware debugger, which the Leonardo doesn't).  I don't have the AVR debugging hardware readily available to really see what's going on, so I don't see this being fixed anytime soon :(
