### ISSUE TITLE
Expand System Control support

### ISSUE THREAD

**Issue by AK5nowman** [microsoft/ArduinoHidForWindows#3]
Does windows support any other usages in system controls? Particularly 'System Speaker Mute' (0xA7), 'System Microphone Mute' (0xA9) and the follow on LED 'System Microphone Mute' (0x57) are of interest. I'm having a hard time finding what is supported and what isn't.

**Comment by matwilli** [comment]
I can't find these Usages mentioned in the public documentation, so they are unlikely to be currently supported.  I wouldn't suggest building anything using them.
