### ISSUE TITLE
Error when compiling for seeeduino xiao samd21 board 

### ISSUE THREAD

**Issue by Nikpesu** [microsoft/ArduinoHidForWindows#5]
I am encountering following error while compiling LampArray in Arduino IDE for Seeeduino XIAO board. I attempted to use PlatformIO, but the same error persists.
```
In file included from c:\Users\nikpe\Documents\Arduino\libraries\ArduinoHidForWindows-Microsoft_HidForWindows-v1.3.0\src/Microsoft_HidConsumerControl.h:12:0,
                 from c:\Users\nikpe\Documents\Arduino\libraries\ArduinoHidForWindows-Microsoft_HidForWindows-v1.3.0\src/Microsoft_HidForWindows.h:6,
                 from C:\Users\nikpe\AppData\Local\Temp\.arduinoIDE-unsaved2024127-180692-fbuc3y.lwjj\LampArray\LampArray.ino:4:
c:\Users\nikpe\Documents\Arduino\libraries\ArduinoHidForWindows-Microsoft_HidForWindows-v1.3.0\src/Microsoft_HidDevice.h:15:1: error: expected class-name before '{' token
 {
 ^

exit status 1

Compilation error: exit status 1
```
![image](https://github.com/microsoft/ArduinoHidForWindows/assets/92652074/6ccbd745-f707-4600-b589-514c799118cb)
Im using this package `https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json`
And this is the board `https://www.seeedstudio.com/Seeeduino-XIAO-Arduino-Microcontroller-SAMD21-Cortex-M0+-p-4426.html`

**Comment by matwilli** [comment]
This library has only been tested on an Arduino Zero (see Caveats on main page).  There are many underlying HID issues on other boards/forks which we are not looking to address.  Feel free to create a PR (for consideration) to support the board of your choice.
